#!/bin/sh
#Scenarios to simulate call flow
SCENARIO_FILE=/root/Plivo/
#media server IP or Remote sending address
MS_IP=phone.plivo.com
LOCAL_IP=10.0.2.15
LOCAL_PORT=5060
SFT_EXE=/root/Plivo/sipp
FULL_PATH=$SCENARIO_FILE$1
#########without log##########
#$SFT_EXE -sf $FULL_PATH -i $LOCAL_IP -p $LOCAL_PORT $MS_IP -m 1
##########with sipp log############
#$SFT_EXE -sf $FULL_PATH -i $LOCAL_IP -p $LOCAL_PORT $MS_IP -m 1 -trace_screen -trace_msg -trace_err 
$SFT_EXE -sf $FULL_PATH -i $LOCAL_IP -p $LOCAL_PORT $MS_IP -m 1 -trace_screen -trace_msg -trace_err 
#$SFT_EXE -sf $FULL_PATH -i $LOCAL_IP -p $LOCAL_PORT $MS_IP -m 1 -trace_screen

